name: Windows Build
on: [push,pull_request,check_run]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Download Haxelib
        run: |
          haxelib install lime 7.9.0 --skip-dependencies --quiet
          haxelib install openfl 9.2.0 --skip-dependencies --quiet
          haxelib install flixel 4.11.0 --skip-dependencies --quiet
          haxelib install flixel-tools 1.5.1 --skip-dependencies --quiet
          haxelib run flixel-tools setup --quiet
          haxelib install flixel-addons 2.11.0 --skip-dependencies --quiet
          haxelib install flixel-ui 2.5.0 --skip-dependencies --quiet
          haxelib install hscript 2.5.0 --skip-dependencies --quiet
          haxelib install newgrounds 1.1.4 --skip-dependencies --quiet
          haxelib install actuate
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git --quiet
          haxelib git faxe https://github.com/uhrobots/faxe --quiet
          haxelib git polymod https://github.com/larsiusprime/polymod.git --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
      - name: Rebuild
        run: |
          haxelib run lime rebuild extension-webm windows
      - name: Build
        run: |
          haxelib run lime build windows
          
      - uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: export/release/windows/bin

